import {GAME_DATA as DATA} from './data.js';
import {DEFAULT_STATE} from './defaults.js';
import {
  optimizePlan,requiredAbilities,pickCoverageCore,buildTeamModel,findBestTeams,optimizePersonalities,
  findEssentialCore,antiStallSummary,itemName,itemValue,livingFacilityGroups,planItemRates,externalInputs,
  defaultRecipeEfficiencyPct
} from './optimizer.js';
import {fillHomelandForRV,progressionSummary} from './progression.js';

const STORE='aniimoHomelandOptimizerStateV1',HIDEOUT='https://www.hideoutgacha.com';
const MAX_ANIIMO_BY_HOMELAND=[0,5,8,11,14,17,20,22,24,26,28,30,32,34,36,38,40,42,43,44,45];
const maxAniimoForLevel=level=>MAX_ANIIMO_BY_HOMELAND[Math.min(20,Math.max(1,Number(level)||1))]||5;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const asset=path=>path?.startsWith('http')?path:`${HIDEOUT}${path||''}`,fmt=n=>Math.round(Number(n||0)).toLocaleString(),fmt1=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:1}),pct=n=>`${(Number(n||0)*100).toFixed(2)}%`,clone=x=>JSON.parse(JSON.stringify(x));
const facilityMap=new Map(DATA.facilities.map(x=>[x.slug,x]));
let state=loadState(),currentPlan=null,currentModel=null,recomputeTimer=null,undoSnapshot=null,undoTimer=null,teamSpeedOverride=null;
function diffCount(a,b){if(a===b)return 0;if(a==null||b==null||typeof a!=='object'||typeof b!=='object')return 1;const keys=new Set([...Object.keys(a),...Object.keys(b)]);let n=0;for(const k of keys){n+=diffCount(a[k],b[k]);if(n>=2)return n;}return n;}
function ensureUndoBar(){if($('#change-undo'))return;document.body.insertAdjacentHTML('beforeend',`<div id="change-undo" class="change-undo"><span><b>Detected a change.</b> Revert?</span><div><button id="undo-change" class="undo-action">REVERT</button><button id="close-undo" class="undo-action muted">CLOSE</button></div></div>`);$('#undo-change').onclick=()=>{if(!undoSnapshot)return;state=normalizeState(undoSnapshot);undoSnapshot=null;saveState();hideUndo();renderAll();history.replaceState(null,'',shareUrl());};$('#close-undo').onclick=hideUndo;}
function hideUndo(){clearTimeout(undoTimer);$('#change-undo')?.classList.remove('show');}
function offerUndo(before){if(diffCount(before,state)<2)return;ensureUndoBar();undoSnapshot=clone(before);$('#change-undo').classList.add('show');clearTimeout(undoTimer);undoTimer=setTimeout(hideUndo,12000);}
function applyAtomicState(next,before=clone(state)){teamSpeedOverride=null;state=normalizeState(next);saveState();renderAll();offerUndo(before);history.replaceState(null,'',shareUrl());}
function effectivePlanState(){if(!teamSpeedOverride)return state;return{...state,speeds:{...state.speeds,...teamSpeedOverride.facilities},realRecipeSpeeds:{...teamSpeedOverride.recipes}};}
function clearTeamSpeedOverride(refresh=true){if(!teamSpeedOverride)return false;teamSpeedOverride=null;if(refresh)renderFacilities();return true;}
function speedOverrideFromSpecial(special){
  const profile=special?.ev?.speedProfile;if(!profile)return null;const facilities={},recipes={},details={};
  for(const[id,v]of Object.entries(profile.recipes||{}))if(Number.isFinite(Number(v?.pct)))recipes[id]=Number(v.pct);
  for(const[slug,v]of Object.entries(profile.facilities||{})){if(!Number.isFinite(Number(v?.pct)))continue;facilities[slug]=Number(v.pct);const workers=(v.workers||[]).map(i=>special.team?.[Number(i)]?.pal?.name).filter(Boolean);details[slug]={pct:Number(v.pct),workers:[...new Set(workers)],recipes:v.recipes||[]};}
  return Object.keys(facilities).length?{facilities,recipes,details}:null;
}

function defaultOwned(){const out={};for(const p of DATA.pals)out[String(p.id)]={enabled:true,count:1};return out;}
function normalizeState(s){
  const x={...clone(DEFAULT_STATE),...clone(s||{})};
  x.facilities={...clone(DEFAULT_STATE.facilities),...(s?.facilities||{})};x.modules={...clone(DEFAULT_STATE.modules),...(s?.modules||{})};x.speeds={...clone(DEFAULT_STATE.speeds),...(s?.speeds||{})};
  x.climateOptions={...clone(DEFAULT_STATE.climateOptions),...(s?.climateOptions||{})};
  if(s?.climate?.enabled&&!s?.climateOptions){const t=s.climate.temperature;if(t==='Cool'||t==='Freeze')x.climateOptions.cooling=true;else if(t==='Warm'||t==='Scorching')x.climateOptions.heat=true;else if(t==='Adequate')x.climateOptions.sunlamp=true;}
  x.homelandLevel=Math.min(20,Math.max(1,Number(x.homelandLevel)||1));const maxSlots=maxAniimoForLevel(x.homelandLevel);x.workerSlots=Math.min(maxSlots,Math.max(1,Number(x.workerSlots)||1));x.teamSlots=Math.min(maxSlots,Math.max(1,Number(s?.teamSlots??s?.workerSlots??x.teamSlots)||1));x.collectHours=Math.max(0,Number(x.collectHours||0));x.oneRecipePerFacility=!!x.oneRecipePerFacility;x.generatorAvailable=!!x.generatorAvailable;x.hungry=!!x.hungry;x.manualSpeeds=!!x.manualSpeeds;
  x.recipeNotes={...(s?.recipeNotes||{})};x.guarantees=Array.isArray(s?.guarantees)?s.guarantees.map(g=>({item:String(g.item||''),perHour:Math.max(0,Number(g.perHour||0)),maximize:!!g.maximize,enabled:g.enabled!==false})):[];x.target=String(x.target||'coin');
  if(!x.owned||!Object.keys(x.owned).length)x.owned=defaultOwned();for(const p of DATA.pals)if(!x.owned[String(p.id)])x.owned[String(p.id)]={enabled:true,count:1};
  return x;
}
function loadState(){try{return normalizeState(JSON.parse(localStorage.getItem(STORE)||'null'));}catch{return normalizeState(null);}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state));}

function parseFacilities(raw){const out={};for(const tok of String(raw||'').split('_')){if(!tok.includes(':'))continue;const[slug,val]=tok.split(':',2),dot=val.lastIndexOf('.'),count=Number(dot>=0?val.slice(0,dot):val),level=Number(dot>=0?val.slice(dot+1):1);if(slug&&Number.isFinite(count)&&Number.isFinite(level))out[slug]={count,level};}return out;}
function parseSimple(raw){const out={};for(const tok of String(raw||'').split('_')){if(!tok.includes(':'))continue;const[k,v]=tok.split(':',2),n=Number(v);if(k&&Number.isFinite(n))out[k]=n;}return out;}
function applyUrl(input){
  const before=clone(state);let u;try{u=new URL(input,location.href);}catch{throw new Error('That does not look like a URL.');}const q=u.searchParams;
  if(q.has('f'))state.facilities=parseFacilities(q.get('f'));if(q.has('m'))state.modules=parseSimple(q.get('m'));if(q.has('y'))state.speeds=parseSimple(q.get('y'));
  if(q.has('h'))state.homelandLevel=Math.max(1,Number(q.get('h'))||1);if(q.has('w'))state.workerSlots=Math.max(1,Number(q.get('w'))||1);if(q.has('tw'))state.teamSlots=Math.max(1,Number(q.get('tw'))||1);
  if(q.has('a'))state.abilityLevel=q.get('a')==='auto'?'auto':Math.max(1,Number(q.get('a'))||1);if(q.has('collect'))state.collectHours=Math.max(0,Number(q.get('collect'))||0);if(q.has('one'))state.oneRecipePerFacility=q.get('one')==='1';
  if(q.has('cl')){const v=new Set(q.get('cl').split('.'));state.climateOptions={cooling:v.has('cooling'),heat:v.has('heat'),sunlamp:v.has('sunlamp')};}
  if(q.has('gen'))state.generatorAvailable=q.get('gen')==='1';if(q.has('hungry'))state.hungry=q.get('hungry')==='1';if(q.has('sm'))state.manualSpeeds=q.get('sm')==='1';if(q.has('target'))state.target=q.get('target')||'coin';
  if(q.has('g'))state.guarantees=q.get('g').split('.').map(x=>{const[id,n]=x.split('-');return{item:id,perHour:Number(n)||0,maximize:false,enabled:true};}).filter(x=>x.item);if(q.has('mx')){const maxItems=new Set(q.get('mx').split('.'));for(const g of state.guarantees)g.maximize=maxItems.has(String(g.item));}if(q.has('gd')){const disabled=new Set(q.get('gd').split('.').map(x=>Number(x)));state.guarantees.forEach((g,i)=>g.enabled=!disabled.has(i));}
  if(q.has('p')){const ids=new Set(q.get('p').split('.').map(String));for(const p of DATA.pals)state.owned[String(p.id)]={enabled:ids.has(String(p.id)),count:state.owned?.[String(p.id)]?.count||1};}
  if(q.has('c'))for(const token of q.get('c').split('.')){const[id,n]=token.split('-');if(state.owned[id])state.owned[id].count=Math.max(1,Number(n)||1);}
  state=normalizeState(state);saveState();renderAll();offerUndo(before);
}
function shareUrl(){
  const u=new URL(location.href);u.search='';const f=Object.entries(state.facilities).filter(([,x])=>Number(x.count)>0).map(([k,x])=>`${k}:${x.count}.${x.level}`).join('_'),m=Object.entries(state.modules).filter(([,v])=>Number(v)>0).map(([k,v])=>`${k}:${v}`).join('_'),y=Object.entries(state.speeds).filter(([,v])=>Number(v)>0).map(([k,v])=>`${k}:${v}`).join('_');
  const owned=DATA.pals.filter(p=>state.owned[String(p.id)]?.enabled).map(p=>p.id).join('.'),copies=DATA.pals.filter(p=>state.owned[String(p.id)]?.enabled&&Number(state.owned[String(p.id)].count)>1).map(p=>`${p.id}-${state.owned[String(p.id)].count}`).join('.'),cl=Object.entries(state.climateOptions).filter(([,v])=>v).map(([k])=>k).join('.'),g=(state.guarantees||[]).filter(x=>x.item).map(x=>`${x.item}-${Number(x.perHour)||0}`).join('.'),mx=(state.guarantees||[]).filter(x=>x.item&&x.maximize).map(x=>x.item).join('.'),gd=(state.guarantees||[]).map((x,i)=>x.enabled===false?i:null).filter(x=>x!=null).join('.');
  for(const[k,v]of[['f',f],['m',m],['y',y],['a',state.abilityLevel],['h',state.homelandLevel],['w',state.workerSlots],['tw',state.teamSlots],['collect',state.collectHours],['one',state.oneRecipePerFacility?1:0],['cl',cl],['gen',state.generatorAvailable?1:0],['hungry',state.hungry?1:0],['sm',state.manualSpeeds?1:0],['target',state.target],['mx',mx],['gd',gd],['p',owned]])if(v!==''&&v!=null)u.searchParams.set(k,String(v));if(copies)u.searchParams.set('c',copies);if(g)u.searchParams.set('g',g);return u.toString();
}

function title(text,aside=''){return`<div class="section-title"><span></span><h3>${esc(text)}</h3><i></i>${aside?`<em class="micro">${aside}</em>`:''}</div>`;}
function update(mut,{rerender=null,plan=true}={}){mut(state);saveState();if(rerender)rerender();if(plan)scheduleCompute();}
function climateCard(key,name,desc){const f=facilityMap.get(key==='cooling'?'cooling-unit':key==='heat'?'heat-furnace':'sunlamp'),on=!!state.climateOptions[key];return`<label class="climate-card ${on?'enabled':''}"><input class="climate-option" data-key="${key}" type="checkbox" ${on?'checked':''}><div class="climate-main"><img src="${asset(f?.icon)}" alt=""><b>${esc(name)}</b></div><small>${esc(desc)}</small></label>`;}
function renderGeneral(){
  const cap=maxAniimoForLevel(state.homelandLevel),rv=progressionSummary(state.homelandLevel,DATA);$('#general-panel').innerHTML=title('Plan settings')+`
    <div class="grid2">
      <div class="field"><label>Homeland level</label><div class="number-with-max"><input id="homeland-level" type="number" min="1" max="20" value="${state.homelandLevel}"><span>/ 20</span></div></div>
      <div class="field"><label>Theoretical plan Aniimo</label><div class="number-with-max"><input id="worker-slots" type="number" min="1" max="${cap}" value="${state.workerSlots}"><span>/ ${cap}</span></div></div>
      <div class="field"><label>Real team Aniimo</label><div class="number-with-max"><input id="team-slots" type="number" min="1" max="${cap}" value="${state.teamSlots}"><span>/ ${cap}</span></div></div>
      <div class="field"><label>Planning ability ceiling</label><select id="ability-level"><option value="auto" ${String(state.abilityLevel)==='auto'?'selected':''}>Auto from enabled roster</option>${[1,2,3,4].map(n=>`<option value="${n}" ${Number(state.abilityLevel)===n?'selected':''}>Lv.${n}</option>`).join('')}</select></div>
      <div class="field"><label>I empty facilities every</label><select id="collect-hours">${[[0,'As often as it takes'],[1,'1 hour'],[2,'2 hours'],[4,'4 hours'],[8,'8 hours'],[12,'12 hours'],[24,'1 day'],[48,'2 days']].map(([v,n])=>`<option value="${v}" ${Number(state.collectHours)===v?'selected':''}>${n}</option>`).join('')}</select></div>
      <div class="field"><label>Global speed</label><div class="quick-row" style="margin:0"><button class="ghost speed-all" data-speed="100">100%</button><button class="ghost speed-all" data-speed="300">300%</button><button class="ghost speed-all" data-speed="400">400%</button></div></div>
    </div>
    <div class="capacity-note"><span>RV ${rv.rv} ceiling · ${rv.bulk.farmland} Farmland · ${rv.bulk.woodland} Woodland · ${rv.bulk.mine} Mine · ${rv.bulk.well} Well</span><button id="fill-rv" class="ghost compact">Fill for RV ${rv.rv}</button></div>
    <div class="grid2" style="margin-top:9px">
      <label class="check-row"><input id="one-recipe" type="checkbox" ${state.oneRecipePerFacility?'checked':''}><span><b>One recipe per facility</b><small>Walk-away mode. Off lets the solver split facility time across recipes for the strongest mathematical mix.</small></span></label>
      <label class="check-row"><input id="generator" type="checkbox" ${state.generatorAvailable?'checked':''}><span><b>Crackle Generator available</b><small>This is permission, not forced placement. The solver tests whether spending one station slot on E-mode is actually worth it.</small></span></label>
      <label class="check-row"><input id="hungry" type="checkbox" ${state.hungry?'checked':''}><span><b>Aniimo are out of food</b><small>Manual worker speed is reduced to 20%. Electric recipes are unaffected.</small></span></label>
    </div>
    <div class="micro-label" style="margin-top:11px">Climate buildings available to the solver</div>
    <div class="climate-grid">${climateCard('cooling','Cooling Unit','May be unused, Cool, or Freeze. The solver tests all three.')}${climateCard('heat','Heat Furnace','May be unused, Warm, or Scorching. The solver chooses.')}${climateCard('sunlamp','Sunlamp','May be unused or provide Adequate recipes.')}</div>
    <p class="micro">Checked means “I could place this if it improves the answer.” It does not mean the building is already committed. Utility buildings only consume a worker when the winning solution actually uses them.</p>`;
  $('#homeland-level').onchange=e=>{state.homelandLevel=Math.min(20,Math.max(1,Number(e.target.value)||1));const m=maxAniimoForLevel(state.homelandLevel);state.workerSlots=Math.min(m,state.workerSlots);state.teamSlots=Math.min(m,state.teamSlots);saveState();renderGeneral();scheduleCompute();};$('#fill-rv').onclick=()=>{const before=clone(state);applyAtomicState(fillHomelandForRV(state,DATA),before);};$('#worker-slots').oninput=e=>update(x=>x.workerSlots=Math.min(maxAniimoForLevel(x.homelandLevel),Math.max(1,Number(e.target.value)||1)));$('#team-slots').oninput=e=>update(x=>x.teamSlots=Math.min(maxAniimoForLevel(x.homelandLevel),Math.max(1,Number(e.target.value)||1)));$('#ability-level').onchange=e=>update(x=>x.abilityLevel=e.target.value==='auto'?'auto':Number(e.target.value));$('#collect-hours').onchange=e=>update(x=>x.collectHours=Number(e.target.value));
  $('#one-recipe').onchange=e=>update(x=>x.oneRecipePerFacility=e.target.checked);$('#generator').onchange=e=>update(x=>x.generatorAvailable=e.target.checked);$('#hungry').onchange=e=>update(x=>x.hungry=e.target.checked);
  document.querySelectorAll('.climate-option').forEach(i=>i.onchange=e=>update(x=>x.climateOptions[e.target.dataset.key]=e.target.checked,{rerender:renderGeneral}));document.querySelectorAll('.speed-all').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.speed);for(const f of DATA.facilities)if(f.kind!=='utility')state.speeds[f.slug]=n;saveState();renderFacilities();scheduleCompute();});
}
function automaticFacilitySpeed(slug){
  const active=(currentPlan?.rows||[]).filter(r=>r.facility===slug&&!r.recipe.electric&&(r.recipe.steps||[]).length);
  if(!active.length)return{pct:100,needs:[],active:false};
  let weighted=0,total=0;const needs=new Set();
  for(const row of active){
    const pct=defaultRecipeEfficiencyPct(row.recipe),weight=Math.max(1e-6,Number(row.batchesPerHour||0)*Math.max(1,Number(row.manualSeconds||1)));
    weighted+=pct*weight;total+=weight;
    for(const step of row.recipe.steps||[])needs.add(`${step.ability} Lv.${step.level}`);
  }
  return{pct:total?weighted/total:100,needs:[...needs],active:true};
}
function renderFacilities(){
  const rows=DATA.facilities.filter(f=>f.kind!=='utility').sort((a,b)=>{const ac=Number(state.facilities[a.slug]?.count||0)>0,bc=Number(state.facilities[b.slug]?.count||0)>0;return Number(bc)-Number(ac)||a.category-b.category||a.name.localeCompare(b.name);}),calibrated=!!teamSpeedOverride,manual=!!state.manualSpeeds;
  $('#facilities-panel').innerHTML=title('Facilities',calibrated?'real-team Efficiency · resets on plan change':manual?'manual Speed % locked':'automatic recipe-aware Efficiency')+`<label class="speed-mode-toggle"><input id="manual-speeds" type="checkbox" ${manual?'checked':''}><span><b>Manual Speed %</b><small>${manual?'Stored custom values are authoritative; Real Team will not overwrite them.':'Off = use each active recipe’s minimum required ability as the theoretical baseline. Real Team may temporarily replace it with actual abilities + personality.'}</small></span></label><div class="facility-head"><span>Facility</span><span>Count</span><span>Level</span><span>Speed %</span></div><div class="facility-list">${rows.map(f=>{const cfg=state.facilities[f.slug]||{count:0,level:1},auto=teamSpeedOverride?.details?.[f.slug],theory=automaticFacilitySpeed(f.slug),speed=manual?(state.speeds[f.slug]??300):(auto?.pct??theory.pct),mode=manual?'MANUAL':auto?'REAL':theory.active?'AUTO':'AUTO · idle',details=manual?'Stored custom Speed %':auto?`Real-team estimate: ${Number(auto.pct).toFixed(1)}% · ${auto.workers.join(', ')||'recommended worker'}`:`${theory.needs.length?theory.needs.join(' · '):'No active worked recipe'} · minimum required ability baseline`;return`<div class="facility-row ${auto&&!manual?'real-speed-row':!manual?'auto-speed-row':''}" data-facility="${f.slug}"><div class="facility-name"><img src="${asset(f.icon)}" alt=""><div><b>${esc(f.name)}</b><small>${esc(f.categoryName||f.kind)} · max Lv.${f.maxLevel} · ${esc(mode)}</small></div></div><input class="fac-count" title="Count" type="number" min="0" max="99" value="${cfg.count}"><input class="fac-level" title="Level" type="number" min="1" max="${f.maxLevel}" value="${cfg.level}"><input class="fac-speed speed-cell ${auto&&!manual?'real-speed':!manual?'auto-speed':''}" title="${esc(details)}" type="number" min="1" max="999" step="0.1" value="${Number(speed).toFixed(1)}" ${manual?'':'readonly'}></div>`;}).join('')}</div>`;
  $('#manual-speeds').onchange=e=>{teamSpeedOverride=null;state.manualSpeeds=e.target.checked;saveState();renderFacilities();scheduleCompute({refreshFacilities:false});};
  document.querySelectorAll('.facility-row').forEach(row=>{const slug=row.dataset.facility;row.querySelector('.fac-count').oninput=e=>facilityUpdate(slug,'count',Math.max(0,Number(e.target.value)||0));row.querySelector('.fac-level').oninput=e=>facilityUpdate(slug,'level',Math.max(1,Number(e.target.value)||1));row.querySelector('.fac-speed').oninput=e=>{if(!state.manualSpeeds)return;state.speeds[slug]=Math.max(1,Number(e.target.value)||100);saveState();scheduleCompute({refreshFacilities:false});};});
}
function facilityUpdate(slug,key,value){if(!state.facilities[slug])state.facilities[slug]={count:0,level:1};state.facilities[slug][key]=value;saveState();scheduleCompute();}
function renderModules(){const mods=[['crafting-module','Crafting Module'],['ecological-module','Ecological Module'],['kitchen-module','Kitchen Module'],['resource-detector','Resource Detector']];$('#modules-panel').innerHTML=title('Upgrade modules')+`<div class="grid2">${mods.map(([k,n])=>`<div class="field"><label>${n}</label><input class="module-level" data-module="${k}" type="number" min="0" max="20" value="${state.modules[k]||0}"></div>`).join('')}</div>`;document.querySelectorAll('.module-level').forEach(i=>i.oninput=e=>update(x=>x.modules[e.target.dataset.module]=Math.max(0,Number(e.target.value)||0)));}
const RECIPE_NOTE_UNLOCKS={'4040114':'RV 7','4040115':'RV 9','4040116':'RV 12','4040117':'RV 16','4040118':'RV 18','4040119':'RV 19'};
function recipeNoteIcon(id){return `${HIDEOUT}/images/aniimo/database/materials/item_${id}.webp`;}
function recipeNotes(){const m=new Map();for(const r of DATA.recipes)if(r.note){const key=String(r.note.item),old=m.get(key),output=(r.outputs||[])[0]?.item;if(!old)m.set(key,{...r.note,outputItem:output,outputName:output?itemName(DATA,output):''});else if(!old.outputItem&&output){old.outputItem=output;old.outputName=itemName(DATA,output);}}const rv=n=>Number((RECIPE_NOTE_UNLOCKS[String(n.item)]||'999').match(/\d+/)?.[0]||999);return[...m.values()].sort((a,b)=>rv(a)-rv(b)||a.name.localeCompare(b.name));}
function renderNotes(){const notes=recipeNotes(),on=notes.filter(n=>state.recipeNotes[String(n.item)]!==false).length;$('#notes-panel').innerHTML=title('Recipe notes',`${on} of ${notes.length} read`)+`<div class="note-grid">${notes.map(n=>{const name=n.name.replace(/^Recipe Note:\s*/,''),unlock=RECIPE_NOTE_UNLOCKS[String(n.item)]||'Recipe Note',output=n.outputItem?itemIcon(n.outputItem):'';return`<label class="note-card"><input class="note-toggle" data-id="${n.item}" type="checkbox" ${state.recipeNotes[String(n.item)]!==false?'checked':''}><div class="note-body"><div class="note-main"><img src="${output||recipeNoteIcon(n.item)}" alt="" onerror="this.style.opacity='.15'"><div><b>${esc(name)}</b>${n.outputName?`<span class="note-unlocks"><img src="${recipeNoteIcon(n.item)}" alt="" onerror="this.style.opacity='.15'"><span>Unlocks ${esc(n.outputName)}</span></span>`:''}</div></div><div class="note-unlock">Unlocked by <b>${esc(unlock)}</b></div></div></label>`;}).join('')}</div><p class="micro">Untick a note you have not read and every recipe gated by it disappears from the solver.</p>`;document.querySelectorAll('.note-toggle').forEach(i=>i.onchange=e=>update(x=>x.recipeNotes[e.target.dataset.id]=e.target.checked,{rerender:renderNotes}));}
function renderLiving(){const groups=livingFacilityGroups(state,DATA),caught=groups.filter(g=>g.owned.length).length;$('#living-panel').innerHTML=title('Aniimo living in facilities',`${caught} of ${groups.length} caught`)+`<p class="micro" style="margin:0 0 8px">No second checklist. This is inferred from the Aniimo roster in the header. If a family is disabled, its resident-only recipes simply stop existing.</p><div class="living-grid">${groups.map(g=>{const fac=facilityMap.get(g.facility),outs=g.outputs.map(x=>x.name).join(' · '),who=g.owned.map(p=>p.name).join(', ');return`<div class="living-card ${g.owned.length?'':'locked'}"><img src="${HIDEOUT}/images/aniimo/heads/${String(g.pet).slice(0,-2)}.webp" alt=""><div><b>${esc(g.petName)}</b><small>${esc(fac?.name||g.facility)} · makes ${esc(outs)}</small><div class="living-state">${g.owned.length?`available via ${esc(who)}`:'family not enabled'}</div></div></div>`;}).join('')}</div>`;}
function renderOwnership(){const enabled=DATA.pals.filter(p=>state.owned[String(p.id)]?.enabled),copies=enabled.reduce((s,p)=>s+Number(state.owned[String(p.id)]?.count||1),0);$('#ownership-panel').innerHTML=title('Aniimo you own',`${enabled.length} species · ${copies} copies`)+`<div class="ownership-tools"><input id="pal-search" placeholder="Filter Aniimo…"><button id="own-all" class="ghost">All</button><button id="own-none" class="ghost">None</button></div><div class="ownership-grid" id="ownership-grid">${DATA.pals.map(p=>palRow(p)).join('')}</div><div class="summary-line"><span>Checkbox = usable species. Number = copies available to the real-team search.</span><span>${enabled.length}/${DATA.pals.length}</span></div>`;bindOwnership();}
function palRow(p){const rec=state.owned[String(p.id)]||{enabled:true,count:1},abilities=Object.entries(p.abilities||{}).map(([a,l])=>abilityPill(a,l,true)).join('');return`<label class="pal-row ${rec.enabled?'':'off'}" data-id="${p.id}" data-name="${esc(p.name.toLowerCase())}"><input class="pal-enabled" type="checkbox" ${rec.enabled?'checked':''}><img src="${palHeadIcon(p)}" onerror="this.style.visibility='hidden'" alt=""><span class="pal-info"><b>${esc(p.name)}</b><span class="pal-abilities">${abilities}</span></span><input class="pal-count" type="number" min="1" max="99" value="${rec.count||1}" title="Copies"></label>`;}
function bindOwnership(){$('#pal-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.pal-row').forEach(r=>r.style.display=!q||r.dataset.name.includes(q)?'grid':'none');};$('#own-all').onclick=()=>{for(const p of DATA.pals)state.owned[String(p.id)].enabled=true;saveState();renderOwnership();renderLiving();scheduleCompute();};$('#own-none').onclick=()=>{for(const p of DATA.pals)state.owned[String(p.id)].enabled=false;saveState();renderOwnership();renderLiving();scheduleCompute();};document.querySelectorAll('.pal-row').forEach(row=>{const id=row.dataset.id;row.querySelector('.pal-enabled').onchange=e=>{state.owned[id].enabled=e.target.checked;saveState();row.classList.toggle('off',!e.target.checked);renderLiving();scheduleCompute();};row.querySelector('.pal-count').oninput=e=>{state.owned[id].count=Math.max(1,Number(e.target.value)||1);saveState();};});}
function targetItems(){const ids=new Set(DATA.recipes.flatMap(r=>(r.outputs||[]).map(o=>Number(o.item))));return[...ids].map(id=>({id,name:itemName(DATA,id),value:itemValue(DATA,id)})).sort((a,b)=>a.name.localeCompare(b.name));}
const HOME_COIN_ICON='https://aniipedia.com/items/v/tl98fh/1010.webp';
const SPECIAL_ITEM_ICONS={
  '110001':`${HIDEOUT}/images/aniimo/database/capture/item_110001.webp`,
  '110002':`${HIDEOUT}/images/aniimo/database/capture/item_110002.webp`,
  '110007':`${HIDEOUT}/images/aniimo/database/capture/item_110007.webp`,
  '150001':`${HIDEOUT}/images/aniimo/database/currency/item_150001.webp`,
  '150002':`${HIDEOUT}/images/aniimo/database/currency/item_150002.webp`,
  '150003':`${HIDEOUT}/images/aniimo/database/currency/item_150003.webp`
};
function itemIcon(value){const id=String(value);return id==='coin'?HOME_COIN_ICON:SPECIAL_ITEM_ICONS[id]||`${HIDEOUT}/images/aniimo/database/materials/item_${id}.webp`;}
const ABILITY_ICONS={
  Fire:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_fire.webp',
  Grass:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_grass.webp',
  Water:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_water.webp',
  Earth:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_earth.webp',
  Lightning:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_electricity.webp',
  Ice:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_ice.webp',
  Wind:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_wind.webp',
  Dark:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_shadow.webp',
  Light:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_bg_light.webp',
  Hauling:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_Img_Ability_Transport.webp',
  Artisanship:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_Img_Ability_Cropping.webp',
  Leisure:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_Img_Ability_Play.webp',
  Perfumery:'https://aniidex.com/_ipx/q_95&s_34x34/images/homeland/UI_Img_Ability_Incense_Making.webp'
};
function abilityIcon(name){return ABILITY_ICONS[name]||'';}
function palHeadIcon(p){return `${HIDEOUT}/images/aniimo/heads/${String(p.id).slice(0,-2)}.webp`;}
function itemInline(qty,item){return `<span class="item-inline"><img src="${itemIcon(item)}" alt="" onerror="this.style.opacity='.15'"><span>${esc(qty)}× ${esc(itemName(DATA,item))}</span></span>`;}
function coinValue(value,decimals=false){return `<span class="coin-value"><img src="${HOME_COIN_ICON}" alt=""><span>${decimals?fmt1(value):fmt(value)}</span></span>`;}
function metricValue(icon,value){return `<span class="metric-value"><img src="${icon}" alt=""><span>${value}</span></span>`;}
function abilityPill(name,level,mini=false){const c=DATA.abilities[name]?.color||'#7f8994';return `<span class="ability-pill ${mini?'mini':''}" style="--ability:${c}"><img src="${abilityIcon(name)}" alt=""><span>${esc(name)}</span><b>Lv.${level}</b></span>`;}
function palFallbackColors(p){const cs=Object.keys(p.abilities||{}).map(a=>DATA.abilities[a]?.color).filter(Boolean);return[cs[0]||'#56616c',cs[1]||cs[0]||'#313943'];}
function palAbilityChip(p,ability){const[a,b]=palFallbackColors(p),src=palHeadIcon(p);return `<span class="pal-ability-chip" data-palette-src="${src}" style="--pal-a:${a};--pal-b:${b}"><img src="${src}" alt="" onerror="this.style.visibility='hidden'"><span><b>${esc(p.name)}</b> · Lv.${p.abilities[ability]}</span></span>`;}
function teamPalChip(member,inner=''){const p=member.pal||member,[a,b]=palFallbackColors(p),src=palHeadIcon(p);return `<span class="pal-ability-chip team-pal-chip" data-palette-src="${src}" style="--pal-a:${a};--pal-b:${b}"><img src="${src}" alt="" onerror="this.style.visibility='hidden'"><span class="team-pal-copy"><b>${esc(p.name)}</b>${inner}</span></span>`;}
function coverageChip(f,v){const fac=facilityMap.get(f),name=fac?.name||f;return `<span class="coverage-chip ${v.hit===v.total?'full':''}">${fac?.icon?`<img src="${asset(fac.icon)}" alt="">`:''}<span>${esc(name)}</span><b>${v.hit}/${v.total}</b></span>`;}
function applyPalGradients(){
  document.querySelectorAll('.pal-ability-chip[data-palette-src]').forEach(el=>{
    if(el.dataset.paletteDone)return;el.dataset.paletteDone='1';const img=new Image();img.crossOrigin='anonymous';
    img.onload=()=>{try{const cv=document.createElement('canvas'),ctx=cv.getContext('2d',{willReadFrequently:true});cv.width=cv.height=28;ctx.drawImage(img,0,0,28,28);const d=ctx.getImageData(0,0,28,28).data,bins=new Map();for(let i=0;i<d.length;i+=4){const a=d[i+3];if(a<110)continue;let r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx<35||mn>235||mx-mn<18)continue;r=Math.round(r/32)*32;g=Math.round(g/32)*32;b=Math.round(b/32)*32;const k=`${r},${g},${b}`;bins.set(k,(bins.get(k)||0)+a/255);}const ranked=[...bins].sort((x,y)=>y[1]-x[1]).map(([k])=>k.split(',').map(Number));if(!ranked.length)return;const first=ranked[0],dist=c=>Math.hypot(c[0]-first[0],c[1]-first[1],c[2]-first[2]),second=ranked.find(c=>dist(c)>85)||ranked[1]||first;el.style.setProperty('--pal-a',`rgb(${first.join(',')})`);el.style.setProperty('--pal-b',`rgb(${second.join(',')})`);}catch{}};
    img.src=el.dataset.paletteSrc;
  });
}
function itemChoice(value){if(String(value)==='coin')return{id:'coin',name:'Home Coin',value:0,icon:itemIcon('coin')};const id=String(value||'');return{id,name:itemName(DATA,id),value:itemValue(DATA,id),icon:itemIcon(id)};}
function pickerMenu(includeCoin,current){
  const items=targetItems(),zero=items.filter(x=>x.value<=0),sold=items.filter(x=>x.value>0);
  const option=x=>`<button type="button" class="item-option ${String(current)===String(x.id)?'selected':''}" data-value="${x.id}" data-search="${esc(String(x.name).toLowerCase())}" role="option" aria-selected="${String(current)===String(x.id)}"><img loading="lazy" decoding="async" src="${itemIcon(x.id)}" alt="" onerror="this.style.opacity='.15'"><span>${esc(x.name)}</span></button>`;
  return `<div class="item-picker-search"><span>⌕</span><input type="search" autocomplete="off" spellcheck="false" placeholder="Search items…" aria-label="Search items"></div><div class="item-picker-list">${includeCoin?option({id:'coin',name:'Home Coin'}):''}<div class="item-group" data-group="zero"><div class="item-group-title">Does not sell</div>${zero.map(option).join('')}</div><div class="item-group" data-group="sold"><div class="item-group-title">Crafting / sellable materials</div>${sold.map(option).join('')}</div><div class="item-picker-empty">No matching items.</div></div>`;
}
function itemPicker(value,includeCoin,picker,index=''){
  const current=itemChoice(value);
  return`<div class="item-picker" data-picker="${picker}" data-i="${index}"><button type="button" class="item-picker-button" aria-haspopup="listbox" aria-expanded="false"><img src="${current.icon}" alt="" onerror="this.style.opacity='.15'"><span>${esc(current.name)}</span><i>⌄</i></button><div class="item-picker-menu" role="listbox">${pickerMenu(includeCoin,value)}</div></div>`;
}
function resetPicker(menu){
  const search=menu.querySelector('.item-picker-search input');if(search)search.value='';
  menu.querySelectorAll('.item-option').forEach(o=>o.hidden=false);
  menu.querySelectorAll('.item-group').forEach(g=>g.hidden=false);
  const empty=menu.querySelector('.item-picker-empty');if(empty)empty.hidden=true;
}
function filterPicker(menu,query){
  const q=String(query||'').trim().toLowerCase(),options=[...menu.querySelectorAll('.item-option')];
  for(const o of options)o.hidden=!!q&&!String(o.dataset.search||'').includes(q);
  for(const g of menu.querySelectorAll('.item-group'))g.hidden=![...g.querySelectorAll('.item-option')].some(o=>!o.hidden);
  const empty=menu.querySelector('.item-picker-empty');if(empty)empty.hidden=options.some(o=>!o.hidden);
}
function bindItemPickers(){
  const closeMenu=menu=>{resetPicker(menu);menu.classList.remove('open');menu.previousElementSibling?.setAttribute('aria-expanded','false');};
  const closeAll=()=>document.querySelectorAll('.item-picker-menu.open').forEach(closeMenu);
  document.querySelectorAll('.item-picker').forEach(p=>{
    const trigger=p.querySelector('.item-picker-button'),menu=p.querySelector('.item-picker-menu'),search=menu.querySelector('.item-picker-search input');
    menu.onclick=e=>e.stopPropagation();
    trigger.onclick=e=>{e.stopPropagation();const opening=!menu.classList.contains('open');closeAll();if(opening){resetPicker(menu);menu.classList.add('open');trigger.setAttribute('aria-expanded','true');setTimeout(()=>search?.focus(),0);}};
    if(search){search.onclick=e=>e.stopPropagation();search.oninput=e=>filterPicker(menu,e.target.value);search.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();closeMenu(menu);trigger.focus();}};}
    p.querySelectorAll('.item-option').forEach(o=>o.onclick=e=>{e.stopPropagation();const value=o.dataset.value;if(p.dataset.picker==='target')state.target=value;else{const i=Number(p.dataset.i);if(state.guarantees[i])state.guarantees[i].item=value;}saveState();renderObjectives();scheduleCompute();});
  });
  if(!document.documentElement.dataset.itemPickerClose){document.addEventListener('click',closeAll);document.documentElement.dataset.itemPickerClose='1';}
}
function renderObjectives(){
  const joint=(state.guarantees||[]).filter(g=>g.enabled!==false&&g.maximize).length,active=(state.guarantees||[]).filter(g=>g.enabled!==false).length;
  $('#objective-panel').innerHTML=title('Objective')+`<div class="field"><label>Maximise</label>${itemPicker(state.target,true,'target')}</div><div class="micro-label objective-subtitle" style="margin-top:10px"><span>Also make at least</span><b>${active}/${(state.guarantees||[]).length} active${joint?` · ${joint} co-max`:''}</b></div><div id="guarantees">${(state.guarantees||[]).map((g,i)=>guaranteeRow(g,i)).join('')}</div><div class="objective-actions"><button id="add-guarantee" class="ghost">+ another requirement</button><button id="clear-guarantees" class="ghost">Clear requirements</button></div><p class="micro">A normal row is a hard minimum in items per hour, and the solver maximises the main Objective around that floor. <b>MAX overrides /h completely</b>: the saved number is paused and the item becomes a normalised co-objective instead.</p>`;
  $('#add-guarantee').onclick=()=>{const first=targetItems()[0];state.guarantees.push({item:String(first?.id||''),perHour:1,maximize:false,enabled:true});saveState();renderObjectives();scheduleCompute();};
  $('#clear-guarantees').onclick=()=>{state.guarantees=[];saveState();renderObjectives();scheduleCompute();};
  document.querySelectorAll('.guarantee-enabled').forEach(i=>i.onchange=e=>{state.guarantees[Number(e.target.dataset.i)].enabled=e.target.checked;saveState();renderObjectives();scheduleCompute();});document.querySelectorAll('.guarantee-rate').forEach(i=>i.oninput=e=>{state.guarantees[Number(e.target.dataset.i)].perHour=Math.max(0,Number(e.target.value)||0);saveState();scheduleCompute();});
  document.querySelectorAll('.guarantee-max').forEach(i=>i.onchange=e=>{state.guarantees[Number(e.target.dataset.i)].maximize=e.target.checked;saveState();renderObjectives();scheduleCompute();});
  document.querySelectorAll('.guarantee-remove').forEach(b=>b.onclick=()=>{state.guarantees.splice(Number(b.dataset.i),1);saveState();renderObjectives();scheduleCompute();});
  bindItemPickers();
}
function guaranteeRow(g,i){const enabled=g.enabled!==false,maxed=!!g.maximize;return`<div class="objective-row ${enabled?'':'disabled'} ${maxed?'maxed':''}"><label class="guarantee-enabled-toggle" title="${enabled?'Disable this requirement without deleting it':'Enable this requirement'}"><input class="guarantee-enabled" data-i="${i}" type="checkbox" ${enabled?'checked':''} aria-label="${enabled?'Disable':'Enable'} requirement"></label>${itemPicker(g.item,false,'guarantee',i)}<label class="rate-field" title="${maxed?'Ignored while MAX is enabled; uncheck MAX to restore this minimum':'Minimum items per hour'}"><input class="guarantee-rate" data-i="${i}" type="number" min="0" step="any" value="${g.perHour||0}" aria-label="How many per hour" ${maxed?'disabled':''}><span>${maxed?'MAX':'/h'}</span></label><label class="maximize-toggle" title="Maximise this item together with the main objective; this replaces the /h minimum"><input class="guarantee-max" data-i="${i}" type="checkbox" ${maxed?'checked':''}><span>MAX</span></label><button class="ghost guarantee-remove" data-i="${i}" aria-label="Remove">×</button></div>`;}

function scheduleCompute({keepTeamSpeeds=false,refreshFacilities=true}={}){if(!keepTeamSpeeds)clearTeamSpeedOverride(refreshFacilities);clearTimeout(recomputeTimer);recomputeTimer=setTimeout(()=>computePlan(),100);$('#team-panel').innerHTML=title('Real team optimizer')+`<div class="empty">Plan changed. Real-team speed calibration was cleared; the next analysis starts from your normal Speed % values.</div>`;}
function computePlan({keepTeam=false}={}){try{const planState=effectivePlanState();currentPlan=optimizePlan(planState,DATA);currentModel=buildTeamModel(currentPlan,planState,DATA);renderPlan();renderOutputs();renderAbilities();if(!state.manualSpeeds||teamSpeedOverride)renderFacilities();if(!keepTeam)renderTeamReady();}catch(e){currentPlan={rows:[],ratePerHour:0,targetRate:0,infeasible:true,scenarioLabel:'Error'};$('#plan-panel').innerHTML=title('Best plan')+`<div class="empty warning">${esc(e.message||e)}</div>`;$('#outputs-panel').innerHTML='';$('#abilities-panel').innerHTML='';if(!keepTeam)renderTeamReady();}}
function objectiveName(){return state.target==='coin'?'Home Coin':itemName(DATA,state.target);}
function renderPlan(){const rows=[...(currentPlan.rows||[])].sort((a,b)=>b.perHour-a.perHour),targetRate=state.target==='coin'?currentPlan.ratePerHour:currentPlan.targetRate;let labor=currentPlan.utilityWorkers||0;for(const r of rows)labor+=r.recipe.pet?r.units:(r.manualSeconds||0)*r.batchesPerHour/3600;$('#plan-panel').innerHTML=title('Best plan',`${rows.length} assignments · ${currentPlan.testedScenarios||1} utility scenarios tested`)+`
  <div class="metric-grid"><div class="metric"><small>${esc(objectiveName())} / hour</small><strong>${metricValue(itemIcon(state.target==='coin'?'coin':state.target),fmt1(targetRate))}</strong><span>${(state.guarantees||[]).some(g=>g.enabled!==false&&g.maximize)?'jointly maximised':'maximised output'}</span></div><div class="metric"><small>Home Coin / hour</small><strong>${metricValue(HOME_COIN_ICON,fmt(currentPlan.ratePerHour))}</strong><span>${fmt(currentPlan.ratePerHour*24)} / day</span></div></div>
  <div class="scenario-bar"><div><b>Utility choice</b><div class="chosen">${esc(currentPlan.scenarioLabel||'No utility building used')}</div></div><span>${currentPlan.utilityWorkers||0} dedicated station slot${currentPlan.utilityWorkers===1?'':'s'} · ${state.oneRecipePerFacility?'walk-away recipes':'mixed recipes'} · ${state.collectHours?`collect every ${state.collectHours}h`:'no collection cap'}</span></div>
  ${currentPlan.infeasible?`<div class="empty warning">No feasible plan satisfies the current requirements.</div>`:rows.length?`<table class="plan-table"><thead><tr><th>Facility</th><th>Produce</th><th>Needs</th><th class="num">Cycle</th><th class="num coin-head"><img src="${HOME_COIN_ICON}" alt="">Coin/h</th></tr></thead><tbody>${rows.map(planRow).join('')}</tbody></table><p class="micro">Estimated active labour: ${labor.toFixed(2)} Aniimo-hours per hour, including resident and utility assignments.</p>`:`<div class="empty">No runnable production chain with the current settings.</div>`}`;}
function duration(s){if(!Number.isFinite(s))return'—';if(s>=3600)return`${(s/3600).toFixed(s%3600?1:0)}h`;if(s>=60)return`${Math.round(s/60)} min`;return`${Math.round(s)}s`;}
function durationHours(h){if(!Number.isFinite(h)||h<=0)return'—';if(h>=48)return`${(h/24).toFixed(1)}d`;if(h>=1)return`${h.toFixed(1)}h`;return`${Math.ceil(h*60)}m`;}
function materialFlows(plan){const map=new Map();for(const row of plan?.rows||[]){const b=Number(row.batchesPerHour||0);for(const o of row.recipe.outputs||[]){const id=Number(o.item),r=map.get(id)||{produced:0,consumed:0};r.produced+=Number(o.qty||0)*b;map.set(id,r);}for(const i of row.recipe.inputs||[]){const id=Number(i.item),r=map.get(id)||{produced:0,consumed:0};r.consumed+=Number(i.qty||0)*b;map.set(id,r);}}return map;}
function flowBadges(row){const flows=materialFlows(currentPlan),ids=[...new Set((row.recipe.inputs||[]).map(x=>Number(x.item)))],badges=[];for(const id of ids){const f=flows.get(id);if(!f||f.produced<=1e-7)continue;const net=f.produced-f.consumed,eps=.05,cls=net>eps?'surplus':net<-eps?'deficit':'balanced',label=net>eps?`+${fmt1(net)}/h left`:net<-eps?`${fmt1(net)}/h short`:'balanced';badges.push(`<span class="flow-badge ${cls}" title="Internal material balance"><img src="${itemIcon(id)}" alt=""><span>${esc(itemName(DATA,id))}</span><span class="flow-ledger">${fmt1(f.produced)} made · ${fmt1(f.consumed)} used</span><b>${label}</b></span>`);}return badges.length?`<div class="flow-badges">${badges.join('')}</div>`:'';}
function planRow(row){const fac=facilityMap.get(row.facility),outs=(row.recipe.outputs||[]).map(o=>itemInline(o.qty,o.item)).join('<span class="item-sep">·</span>'),ins=(row.recipe.inputs||[]).map(i=>itemInline(i.qty,i.item)).join('<span class="item-sep">·</span>')||'<span class="nothing">nothing</span>',fraction=row.units>=.995?`${row.units.toFixed(row.units>=10?0:1)}×`:`${Math.round(row.units*100)}%`,steps=(row.recipe.steps||[]).map(s=>abilityPill(s.ability,s.level)).join(''),extras=[row.recipe.pet?`resident ${row.recipe.petName||'family'}`:'',row.recipe.electric?'E-mode':''].filter(Boolean),needs=steps?`<div class="needs-list">${steps}</div>${extras.length?`<div class="need-extra">${esc(extras.join(' · '))}</div>`:''}`:`<span class="no-manual">No manual job</span>${extras.length?`<div class="need-extra">${esc(extras.join(' · '))}</div>`:''}`;return`<tr><td><div class="prod"><img src="${asset(fac?.icon)}" alt=""><span>${fraction} ${esc(fac?.name||row.facility)}</span></div></td><td><div class="recipe-items"><b>${outs}</b><div class="subtle from-line">from ${ins}</div>${flowBadges(row)}</div></td><td class="req">${needs}</td><td class="num">${duration(row.cycleSeconds)}</td><td class="num coin-cell"><b>${coinValue(row.perHour)}</b></td></tr>`;}
function outputKinds(){const primary=new Set(),secondary=new Set(),used=new Set();for(const row of currentPlan?.rows||[]){for(const input of row.recipe.inputs||[])used.add(Number(input.item));(row.recipe.outputs||[]).forEach((o,i)=>(i===0?primary:secondary).add(Number(o.item)));}return{primary,secondary,used};}
function sparkline(item,rate,kind='utility'){const palette=kind==='sell'?['#67d98b','#b4f4c7']:kind==='byproduct'?['#e6b85c','#f6dda3']:kind==='input'?['#ff6178','#ff9aaa']:['#74aef2','#b7d6fb'],seed=(Number(item)||String(item).split('').reduce((s,c)=>s+c.charCodeAt(0),0))+Math.round(Number(rate||0)*10),vals=[];for(let i=0;i<8;i++){const wave=Math.sin((seed%37+i*1.73)*.77)*.22,step=((seed*(i+5)*17)%29)/100;vals.push(Math.max(.08,Math.min(.95,.48+wave+step)));}vals[7]=Math.max(.18,Math.min(.94,.38+(Math.log10(Math.max(1,Number(rate||1)))%1)*.48));const pts=vals.map((v,i)=>`${(i*11.7).toFixed(1)},${(25-v*20).toFixed(1)}`).join(' '),last=pts.split(' ').at(-1).split(','),gid=`sp-${String(item).replace(/[^a-zA-Z0-9]/g,'')}-${kind}`;return`<svg class="sparkline" viewBox="0 0 82 30" aria-hidden="true"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${palette[0]}" stop-opacity=".42"/><stop offset="100%" stop-color="${palette[0]}" stop-opacity="0"/></linearGradient></defs><polygon class="area" points="0,29 ${pts} 82,29" fill="url(#${gid})"/><polyline class="line" points="${pts}" stroke="${palette[0]}"/><circle class="dot" cx="${last[0]}" cy="${last[1]}" r="2.3" stroke="${palette[1]}"/></svg>`;}
function renderOutputs(){if(!currentPlan?.rows?.length){$('#outputs-panel').innerHTML=title('What you end up with')+`<div class="empty">Nothing is running.</div>`;return;}const rates=planItemRates(currentPlan,DATA),positive=rates.filter(x=>x.rate>1e-7).sort((a,b)=>b.coinPerHour-a.coinPerHour||b.rate-a.rate).slice(0,16),external=externalInputs(currentPlan,DATA).sort((a,b)=>b.costPerHour-a.costPerHour).slice(0,8),kinds=outputKinds();$('#outputs-panel').innerHTML=title('What you end up with')+`<div class="output-grid">${positive.map(x=>{const item=Number(x.item),secondaryOnly=kinds.secondary.has(item)&&!kinds.primary.has(item),byproduct=x.value>0&&secondaryOnly&&!kinds.used.has(item),kind=x.value<=0?'utility':secondaryOnly&&kinds.used.has(item)?'utility':byproduct?'byproduct':'sell',detail=x.value<=0?'progression / utility output':byproduct?`${fmt(x.value)} coin each · sellable byproduct`:kind==='utility'?`${fmt(x.value)} coin each · retained for production`:`${fmt(x.value)} coin each · sell output`;return`<div class="output-card ${kind}"><div class="output-info"><img src="${itemIcon(x.item)}" alt="" onerror="this.style.opacity='.15'"><div><b>${esc(x.name)}</b><small>${detail}</small></div></div><strong>${fmt1(x.rate)}/h</strong>${sparkline(x.item,x.rate,kind)}</div>`;}).join('')}</div>${external.length?`<div class="subhead">External inputs / seeds to buy</div><div class="output-grid">${external.map(x=>`<div class="output-card input"><div class="output-info"><img src="${itemIcon(x.item)}" alt="" onerror="this.style.opacity='.15'"><div><b>${esc(x.name)}</b><small>${x.value?`${fmt(x.costPerHour)} coin/h cost`:'external input'}</small></div></div><strong class="negative">${fmt1(x.perHour)}/h</strong>${sparkline(x.item,x.perHour,'input')}</div>`).join('')}</div>`:''}`;}
function renderAbilities(){const req=requiredAbilities(currentPlan),enabled=DATA.pals.filter(p=>state.owned[String(p.id)]?.enabled),core=pickCoverageCore(req,state.teamSlots,enabled);$('#abilities-panel').innerHTML=title('Abilities needed',`${core.core.length} minimum coverage · ${Math.max(0,state.teamSlots-core.core.length)} real-team slots spare`)+`<div class="ability-grid">${req.map(r=>{const c=DATA.abilities[r.ability]?.color||'#888',options=enabled.filter(p=>Number(p.abilities?.[r.ability]||0)>=r.level).sort((a,b)=>Number(b.abilities[r.ability])-Number(a.abilities[r.ability])).slice(0,4),copies=enabled.filter(p=>Number(p.abilities?.[r.ability]||0)>=r.level).reduce((s,p)=>s+Number(state.owned[String(p.id)]?.count||1),0);return`<div class="ability-card" style="--ability:${c}"><div class="ability-head"><div>${abilityPill(r.ability,r.level)}</div><span>${r.count} jobs</span></div><p>${esc(r.jobs.join(', '))}</p><div class="coverage-note">${copies} enabled copies can cover this</div><div class="chips pal-ability-list">${options.map(p=>palAbilityChip(p,r.ability)).join('')}</div></div>`;}).join('')}</div>${core.uncovered.length?`<p class="warning">Roster cannot cover: ${core.uncovered.map(x=>`${x.ability} Lv.${x.level}`).join(', ')}</p>`:''}`;applyPalGradients();}
function renderTeamReady(){$('#team-panel').innerHTML=title('Real team optimizer')+`<div class="team-toolbar"><button id="analyze-team" class="primary">Analyze ${state.teamSlots}-Aniimo real team</button><span id="team-status" class="status">Uses enabled copies, actual abilities, resident families, utility jobs and the full runnable recipe pool.</span></div><p class="micro">The theoretical plan above uses ${state.workerSlots} generic station slots. This pass is separate on purpose: it asks what your ${state.teamSlots}-Aniimo roster can actually achieve, and it is free to rebalance recipes around the team instead of merely checking whether it can imitate the generic plan.</p><div id="team-results"></div>`;$('#analyze-team').onclick=analyzeTeam;}
async function analyzeTeam(){const btn=$('#analyze-team'),status=$('#team-status'),box=$('#team-results');btn.disabled=true;box.innerHTML='';try{if(teamSpeedOverride){teamSpeedOverride=null;computePlan({keepTeam:true});renderFacilities();}const teams=await findBestTeams(currentModel,currentModel.state||state,DATA,{limit:4,onProgress:t=>status.innerHTML=`<span class="loader"></span> ${esc(t)}`});if(!teams.length)throw new Error('No valid team found.');const best=teams[0],core=findEssentialCore(currentModel,best.team,best.eval.objectiveRate),anti=antiStallSummary(currentModel,best.team,core,best.eval.rows);let special=null;for(let i=0;i<Math.min(3,teams.length);i++){status.innerHTML=`<span class="loader"></span> Measured-speed personality pass ${i+1}/${Math.min(3,teams.length)}`;const ev=await optimizePersonalities(currentModel,teams[i].team,t=>status.innerHTML=`<span class="loader"></span> ${esc(t)}`,teams[i].eval,teams[i].burst);if(!special||ev.objectiveRate>special.ev.objectiveRate)special={team:teams[i].team,ev};}teamSpeedOverride=state.manualSpeeds?null:speedOverrideFromSpecial(special);if(teamSpeedOverride){computePlan({keepTeam:true});renderFacilities();}status.textContent=state.manualSpeeds?`Done · manual Speed % stayed locked; roster and personality roles calculated`:teamSpeedOverride?`Done · measured Efficiency applied until the next plan change`:`Done · actual roster optimum and personality roles calculated`;box.innerHTML=(special?renderSpecial(special):'')+teams.map((x,i)=>renderTeamCard(x,i,i===0?{core,anti}:null)).join('');applyPalGradients();}catch(e){status.textContent=e.message||String(e);box.innerHTML=`<div class="empty warning">${esc(e.message||e)}</div>`;}finally{btn.disabled=false;}}
function traitMarkup(h){return`<span class="traits">${(h?.display||[]).map(x=>{const names=(x.facilities||[]).map(f=>facilityMap.get(f)?.name||f),boost=names.length?` · +20% to ${names.join(', ')}`:'';return`<span class="trait ${x.status}" title="${esc(x.status==='must'?`Required for primary role${boost}`:x.status==='nice'?`Useful secondary role${boost}`:'No relevant preference')}">${esc(x.char)}</span>`;}).join('')}</span>`;}
function speedCalibrationMarkup(s){const rows=Object.entries(s?.ev?.speedProfile?.facilities||{}).sort((a,b)=>Number(b[1]?.pct||0)-Number(a[1]?.pct||0));if(!rows.length)return'';return`<div class="speed-calibration"><div class="subhead">Measured real-team Efficiency</div><div class="speed-calibration-grid">${rows.map(([slug,v])=>{const fac=facilityMap.get(slug),workers=(v.workers||[]).map(i=>s.team?.[Number(i)]?.pal?.name).filter(Boolean);return`<span class="speed-chip" title="${esc(workers.join(', ')||'Recommended worker')}">${fac?.icon?`<img src="${asset(fac.icon)}" alt="">`:''}<span>${esc(fac?.name||slug)}</span><b>${fmt1(v.pct)}%</b></span>`;}).join('')}</div><p class="micro">These are the facility-screen Efficiency values implied by the selected Aniimo, recipe requirement and recommended personality. They are applied to the plan above until you change any plan setting.</p></div>`;}
function renderSpecial(s){const base=state.target==='coin'?currentPlan.ratePerHour:currentPlan.targetRate,actual=state.target==='coin'?s.ev.rate:s.ev.targetRate,ratio=base?actual/base:0,delta=actual-base;return`<div class="result-card special"><div class="result-label">Special #1 · ideal legal personalities for the real team</div><div class="result-rate">${fmt1(actual)} ${esc(objectiveName())}/h</div><div class="result-delta">${pct(ratio)} of generic objective · ${delta>=0?'+':''}${fmt1(delta)}/h · ${fmt(s.ev.rate)} coin/h</div><div class="chips team-chip-grid">${s.team.map((x,i)=>teamPalChip(x,traitMarkup(s.ev.traitHints?.[i]))).join('')}</div>${speedCalibrationMarkup(s)}<p class="micro"><span style="color:var(--green)">Green</span> letters belong to the worker's primary assigned structure and are kept mandatory. <span style="color:var(--amber)">Yellow</span> letters improve other plan jobs that Aniimo can cover. Hover a letter to see the exact structure receiving <b>+20%</b>. <b>o</b> means the pair is irrelevant.</p></div>`;}
function renderTeamCard(x,index,staff){const base=state.target==='coin'?currentPlan.ratePerHour:currentPlan.targetRate,actual=state.target==='coin'?x.eval.rate:x.eval.targetRate,ratio=base?actual/base:0,delta=actual-base;let extra='';if(staff){const{core,anti}=staff;extra+=`<div class="subhead">Essential core · ${core.length}</div><div class="chips team-chip-grid">${core.map(teamPalChip).join('')}</div>`;if(anti.reserves.length)extra+=`<div class="subhead">Anti-stall / spare coverage · ${anti.reserves.length}</div><div class="chips team-chip-grid">${anti.reserves.map(teamPalChip).join('')}</div>`;extra+=`<div class="subhead">Basic-material burst coverage</div><div class="coverage">${[...anti.byFacility].map(([f,v])=>coverageChip(f,v)).join('')}</div>`;}return`<div class="result-card ${index===0?'best':''}"><div class="result-label">${index===0?'Best actual roster plan':`Alternative ${index+1}`}</div><div class="result-rate">${fmt1(actual)} ${esc(objectiveName())}/h</div><div class="result-delta">${pct(ratio)} of theoretical · ${delta>=0?'+':''}${fmt1(delta)}/h · ${fmt(x.eval.rate)} coin/h</div><div class="chips team-chip-grid">${x.team.map(teamPalChip).join('')}</div><div class="subhead">Plan rebalanced for this team · ${x.eval.rows.length} assignments</div>${extra}</div>`;}

function renderAll(){teamSpeedOverride=null;renderObjectives();renderGeneral();renderFacilities();renderModules();renderNotes();renderLiving();renderOwnership();computePlan();}
window.__aniimoOptimizerBridge={getState:()=>clone(state),normalizeState,applyAtomicState,maxAniimoForLevel,shareUrl,analyzeTeam:()=>analyzeTeam()};
function setOwnershipOpen(open){const overlay=$('#ownership-overlay'),toggle=$('#ownership-toggle');overlay.classList.toggle('open',open);overlay.setAttribute('aria-hidden',open?'false':'true');toggle.setAttribute('aria-expanded',open?'true':'false');if(open)setTimeout(()=>$('#pal-search')?.focus(),0);}
$('#ownership-toggle').onclick=()=>setOwnershipOpen(!$('#ownership-overlay').classList.contains('open'));
$('#ownership-close').onclick=()=>setOwnershipOpen(false);
$('#ownership-overlay').onclick=e=>{if(e.target===$('#ownership-overlay'))setOwnershipOpen(false);};
document.addEventListener('keydown',e=>{if(e.key==='Escape')setOwnershipOpen(false);});
$('#import-btn').onclick=()=>{try{applyUrl($('#import-url').value.trim());$('#import-url').value='';}catch(e){alert(e.message);}};$('#reset-btn').onclick=()=>{if(confirm('Reset the optimizer to project defaults?')){state=normalizeState(null);saveState();renderAll();}};$('#copy-link').onclick=async()=>{const url=shareUrl();await navigator.clipboard.writeText(url);$('#copy-link').textContent='Copied';setTimeout(()=>$('#copy-link').textContent='Copy share link',1200);history.replaceState(null,'',url);};$('#data-version').textContent=`DATA ${DATA.version}`;
if([...new URL(location.href).searchParams.keys()].some(k=>['f','m','y','a','h','w','tw','p','c','collect','one','cl','gen','hungry','sm','target','g','mx','gd'].includes(k))){try{applyUrl(location.href);}catch{renderAll();}}else renderAll();
